FROM python:3.10-slim

WORKDIR /app
RUN pip install streamlit pandas numpy

COPY dashboard /app
COPY model /app/model

EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
